### ISSUE TITLE
metar_decode command can't handle large data

### ISSUE THREAD

**Issue by metroid2012** [prcwiek/pmetar#5]
Hi,
i want to decode a station metar data with the "metar_decode" command. when i run it over a short period (less than a year) i works fine, but when i want 3 or 4 years period the package returns an error : 
"pmetar package error: it is not a metar weather report!"
while it is really a weather report. I used the following code:
NFTL<-metar_get_historical("NFTL", start_date = "2021-01-01", end_date = "2021-12-01", from = "iastate")
decoded_NFTL <- metar_decode(NFTL, metric = TRUE, altimeter = FALSE)

**Comment by prcwiek** [comment]
Hi,
I looked at data your downloaded and it seems that in several lines there are "METAR COR" instead of "METAR". Please try the below solutions and let me know if it works for you.

NFTL[c(1152, 1864, 3359, 4093, 4312, 4481)]
NFTL[c(1152, 1864, 3359, 4093, 4312, 4481)] <- stringr::str_replace(NFTL[c(1152, 1864, 3359, 4093, 4312, 4481)], pattern = "COR ", replacement = "")

Now it should be possible to decode NFTL. I will introduce a better handling of errors like this in the next version of the package.

**Comment by prcwiek** [comment]
The package version 0.3.3 is available on CRAN.
